name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test-parse-world-forge:
    name: Data Files
    runs-on: windows-2025
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        path: test-parse-action
        clean: true
    - name: Run this action
      uses: ./test-parse-action
      with:
        repository: EndlessSkyCommunity/world-forge

  test-parse-high-dpi:
    name: High DPI Assets
    runs-on: windows-2025
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        path: test-parse-action
        clean: true
    - name: Run this action
      uses: ./test-parse-action
      with:
        repository: endless-sky/endless-sky-high-dpi
        parse-assets: true